# Test result

/Users/zhe.chen/PycharmProjects/exercism-python-track/.venv/bin/python -X pycache_prefix=/Users/zhe.chen/Library/Caches/JetBrains/PyCharm2025.1/cpython-cache /Applications/PyCharm.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py --multiprocess --qt-support=auto --client 127.0.0.1 --port 61727 --file /Applications/PyCharm.app/Contents/plugins/python-ce/helpers/pycharm/_jb_pytest_runner.py --path /Users/zhe.chen/PycharmProjects/exercism-python-track/basics/guidos_gorgeous_lasagna/lasagna_test.py 
Testing started at 23:30 ...
Connected to pydev debugger (build 251.26927.74)
Launching pytest with arguments /Users/zhe.chen/PycharmProjects/exercism-python-track/basics/guidos_gorgeous_lasagna/lasagna_test.py --no-header --no-summary -q in /Users/zhe.chen/PycharmProjects/exercism-python-track/basics/guidos_gorgeous_lasagna

============================= test session starts ==============================

collecting ... collected 5 items

lasagna_test.py::LasagnaTest::test_EXPECTED_BAKE_TIME PASSED             [ 20%]
lasagna_test.py::LasagnaTest::test_bake_time_remaining PASSED            [ 40%]
lasagna_test.py::LasagnaTest::test_docstrings_were_written PASSED        [ 60%]
lasagna_test.py::LasagnaTest::test_elapsed_time_in_minutes PASSED        [ 80%]
lasagna_test.py::LasagnaTest::test_preparation_time_in_minutes PASSED    [100%]

======================== 5 passed, 5 warnings in 0.02s =========================

Process finished with exit code 0
